# -*- coding: utf-8 -*-
"""gestion_libreria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uQHzXRTvW4vlnhZEYDDzMb74fdwDZOpx
"""

## Requerimiento 1: Definir variables básicas y tipos de datos:
libros=[{"titulo":"Tokio Blues", "autor":"Haruki Murakami", "precio":15500, "stock":43},
    {"titulo":"La vegetariana", "autor":"Han Kang", "precio":14400, "stock":10},
    {"titulo":"El Conde de Montecristo", "autor":"Alexandre Dumas", "precio": 25000, "stock":7},
    {"titulo":"Kokoro", "autor":"Natsume Soseki", "precio":30410, "stock":20},
    {"titulo":"El extranjero", "autor":"Albert Camus", "precio":26170, "stock":15}]
#print(libros)

## Control de Flujos
def mostrar_libros_disponibles():
  for libro in libros:
    if libro.get("stock")>1:
      print(libro)
mostrar_libros_disponibles()

## 3. Condiciones y operadores
minimo=float(input("Ingrese un precio mínimo"))
maximo=float(input("Ingrese un precio máximo"))

for libro in libros:
  if libro.get("precio")>=minimo and libro.get("precio")<=maximo:
    print(libro)

#4. y 6. Simular compra y gestión de descuentos
descuentos = {
    "Haruki Murakami": 0.10,    # 10% de descuento
    "Albert Camus": 0.05        # 5% de descuento
}

def comprar_libros(titulo, cantidad, total_libros_comprados, monto_total_pagado, ahorro_total):
    for libro in libros:
        if libro['titulo'].lower() == titulo.lower():
            if libro['stock'] >= cantidad:
                precio_unitario = libro["precio"]
                subtotal = precio_unitario * cantidad

                autor = libro["autor"]
                descuento = descuentos.get(autor, 0)
                ahorro = subtotal * descuento
                total = subtotal - ahorro

                libro["stock"] -= cantidad

                # Acumulación de compras
                total_libros_comprados += cantidad
                monto_total_pagado += total
                ahorro_total += ahorro

                print(f"\nCompra exitosa:")
                print(f"{cantidad} x '{libro['titulo']}' a ${precio_unitario} c/u")
                if descuento > 0:
                    print(f"Descuento aplicado: {int(descuento * 100)}% (-${ahorro:.2f})")
                print(f"Monto total a pagar: ${total:.2f}")
                return total_libros_comprados, monto_total_pagado, ahorro_total
            else:
                print(f"\nError: Solo hay {libro['stock']} unidades disponibles de '{libro['titulo']}'")
                return total_libros_comprados, monto_total_pagado, ahorro_total
    print(f"\nError: El libro '{titulo}' no está en el inventario.")
    return total_libros_comprados, monto_total_pagado, ahorro_total
total_libros_comprados = 0
monto_total_pagado = 0
ahorro_total = 0

print("Bienvenido a Libros y Bytes")

#5. Menú de opciones
while True:
    print("\n--- Sistema de Compras ---")
    print("1. Mostrar libros disponibles")
    print("2. Filtrar libros por rango de precios")
    print("3. Comprar libro")
    print("4. Finalizar compra y mostrar factura")

    opcion = input("Seleccione una opción (1-4): ")

    if opcion == "1":
        mostrar_libros_disponibles()

    elif opcion == "2":
        try:
            minimo = float(input("Ingrese un precio mínimo: "))
            maximo = float(input("Ingrese un precio máximo: "))
            for libro in libros:
                if minimo <= libro["precio"] <= maximo:
                    print(libro)
        except ValueError:
            print("Por favor ingrese un valor numérico válido.")

    elif opcion == "3":
        titulo = input("Ingrese el título del libro que desea comprar: ")
        try:
            cantidad = int(input("Ingrese la cantidad que desea comprar: "))
            total_libros_comprados, monto_total_pagado, ahorro_total = comprar_libros(titulo, cantidad, total_libros_comprados, monto_total_pagado, ahorro_total)
        except ValueError:
            print("Por favor ingrese un número válido.")
#7. simulación de factura
    elif opcion == "4":
        print("\n----- Factura Final -----")
        print(f"Total de libros comprados: {total_libros_comprados}")
        print(f"Monto total pagado: ${monto_total_pagado:.2f}")
        print(f"Ahorro total por descuentos: ${ahorro_total:.2f}")
        print("-------------------------")
        print("Gracias por visitar Libros & Bytes. ¡Hasta pronto!")
        break

    else:
        print("Opción inválida. Intente nuevamente.")