# -*- coding: utf-8 -*-
"""ConsolidadoGITHUB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AlQIzuw1PoCWNxssxS1TMsMF04CJXFmz
"""

import pandas as pd

# URL del archivo raw de GitHub
url = "https://raw.githubusercontent.com/Aconstanza/Portafolio/refs/heads/main/migracion.csv"


df = pd.read_csv(url)
df.head()

print("------------------------------------------------------")
print("1. LIMPIEZA Y TRANSFORMACIÓN DE DATOS")
print("------------------------------------------------------")
#IDENTIFICACIÓN DE VALORES PERDIDOS
print(df.isnull())
print(df.isnull().sum())
#No hay valores perdidos
print("------------------------------------------------------")
#Tratamiento de valores perdidos
df_limpio = df.dropna()

print("------------------------------------------------------")
#Rango Intercuartílico
Q1= df["Cantidad_Migrantes"].quantile(0.25) #primer cuartil
Q3 = df["Cantidad_Migrantes"].quantile(0.75) #tercer cuartil
IQR = Q3 - Q1 #Rango intercuartil
print(IQR)
print("------------------------------------------------------")
#Filtro de outliers mediante IQR
df_filtrado = df[(df["Cantidad_Migrantes"] >= Q1 - 1.5*IQR) & (df["Cantidad_Migrantes"] <= Q3 + 1.5*IQR)]
df_filtrado.head()
print(df_filtrado)
print("------------------------------------------------------")
#Reemplazo de valores mediante diccionario
reemplazo = {
    "Económica" : "Trabajo",
    "Conflicto" : "Guerra",
    "Educativa" : "Académica"}
df["Razon_Migracion"] = df["Razon_Migracion"].replace(reemplazo)
print(df)
print("------------------------------------------------------")
print("2. ANÁLISIS EXPLORATORIO")
print("------------------------------------------------------")
#Muestra 5 primeras filas del dataset
df.head()
print("------------------------------------------------------")
#Info general del dataset
df.info()
df.describe()
print("------------------------------------------------------")
print("--------Estadisticas Claves--------")

print(df["Cantidad_Migrantes"].mean())
print(df["Cantidad_Migrantes"].median())
print("------------------------------------------------------")
print(df["PIB_Origen"].mean())
print(df["PIB_Destino"].mean())
print("------------------------------------------------------")
print(df["Razon_Migracion"].value_counts())
print("------------------------------------------------------")
print("3 Agrupamiento y Sumarización de Datos")
print("------------------------------------------------------")
#Agrupamiento por razón de migración
df_grouped = df.groupby("Razon_Migracion")["Cantidad_Migrantes"].sum()
print(df_grouped)
print("------------------------------------------------------")
#Media de Indice de desarrollo humano por razón de migración
media_IDH = df.groupby("Razon_Migracion")["IDH_Origen"].mean()
print(media_IDH)
print("------------------------------------------------------")
#orden de cantidad de migrantes mayor a menor
df_orden = df.sort_values(by="Cantidad_Migrantes", ascending=False)
print(df_orden)
print("------------------------------------------------------")
print("4. Filtros y Selección de Datos")
print("------------------------------------------------------")
#Migraciones por conflicto
migra_conflicto = df[df["Razon_Migracion"] == "Guerra"]
print(migra_conflicto)
print("------------------------------------------------------")
#Indice de desarrollo humano mayor a 0.90
idh_destino = df[df["IDH_Destino"] >= 0.90]
print(idh_destino)
print("------------------------------------------------------")
#Diferencia de IDH entre pais de origen y de destino
df["Diferencia_IDH"] = df["IDH_Destino"] - df["IDH_Origen"]
print(df)
print("------------------------------------------------------")
print("5. Exportación de datos")
print("------------------------------------------------------")
df.to_csv("Migracion_Limpio.csv", index=False)

